name: flutter_todo_firebase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  flutter_animate: ^4.3.0
  google_sign_in: ^6.2.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  intl: ^0.20.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
