// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZex4ga4k4uhW8kZuuEnjHbuC7Nvqzmtg',
    appId: '1:148371012524:web:1cf8df17fb8ad2405e1809',
    messagingSenderId: '148371012524',
    projectId: 'todoapplistmdi',
    authDomain: 'todoapplistmdi.firebaseapp.com',
    storageBucket: 'todoapplistmdi.firebasestorage.app',
    measurementId: 'G-YLP9YQ0JSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD60NpmPwneOjpqK2yKGZH10AG67UZnOww',
    appId: '1:148371012524:android:e5666d93ffe257d75e1809',
    messagingSenderId: '148371012524',
    projectId: 'todoapplistmdi',
    storageBucket: 'todoapplistmdi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3MePHfxWVCKJV5m8jZq1hnAOqsgIs0-I',
    appId: '1:148371012524:ios:554ccf95e12b5c4f5e1809',
    messagingSenderId: '148371012524',
    projectId: 'todoapplistmdi',
    storageBucket: 'todoapplistmdi.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3MePHfxWVCKJV5m8jZq1hnAOqsgIs0-I',
    appId: '1:148371012524:ios:554ccf95e12b5c4f5e1809',
    messagingSenderId: '148371012524',
    projectId: 'todoapplistmdi',
    storageBucket: 'todoapplistmdi.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZex4ga4k4uhW8kZuuEnjHbuC7Nvqzmtg',
    appId: '1:148371012524:web:4593254aea922d235e1809',
    messagingSenderId: '148371012524',
    projectId: 'todoapplistmdi',
    authDomain: 'todoapplistmdi.firebaseapp.com',
    storageBucket: 'todoapplistmdi.firebasestorage.app',
    measurementId: 'G-4241VBG5LS',
  );

}